# Stage 1: Build Angular
FROM node:20 AS build

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npx ng build --configuration production

# Stage 2: Servir con Apache
FROM httpd:latest

# Copiar build de Angular a la carpeta de Apache
COPY --from=build /app/dist/frontend/browser/ /usr/local/apache2/htdocs/

# Exponer puerto 80
EXPOSE 8080

# Comando por defecto de Apache
CMD ["httpd-foreground"]
